### ISSUE TITLE
`series` for CSWP is incorrect?

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-nist#71]
https://github.com/ietf-ribose/relaton-data-nist/blob/7725aed2b135149ed242b97bc0bff3258968a494/data/NIST_CSWP_02042022-5.yaml#L37-L41

The series here:
```yaml
series:
- title:
    content: NIST
    format: text/plain
  number: NIST CSWP 02042022-5
```

It should be:
```yaml
series:
- title:
    content: NIST Cybersecurity White Paper
    format: text/plain
  number: NIST CSWP
```
